name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    ## dijalankan pada ubuntu versi terbaru
    runs-on: ubuntu-latest

    ## untuk melakukan login, kita menggunakan script bawaan dari github action
    ## defaultnya itu cuman ngebuild, ga ngepush
    steps:
      - uses: actions/checkout@v3
      - name: Login to Dockerhub
        uses: Docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and Push to Docker
        uses: Docker/build-push-action@v2
        with:
          push: true
          tags: catherinevania/helloworld:v${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      ##SSH itu lebih aman, ada enkripsinya, jadi kita dapat meningkatkan keamanan VM kita supaya ga diakses orang lain
      ##SSH punya password juga yaitu privatekey
      ##EC2 layanan AWS yang digunakan untuk menjalankan virtual machine di cloud yang bisa diakses menggunakan IP public
      #HOST dan privatekey dapet dari AWS
      - name: Connect to EC2 with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.AWS_PRIVATEKEY}}
          username: ubuntu
          port: 22
          ##1. pas udah masuk ke VM, harus memberhentikan container yang lagi berjalan (kalo ada, kalo gaada cumaan ngasih
          ##   warning, ga error)
          ##2. ngeremove container, karena mau ngestart container baru dengan nama yang sama (gaboleh ada 2 container
          ##   yang namanya sama)
          ##3. ngepull image
          ##4. ngebuat container baru dengan nama helloworld dan port 80 (HTTP, jadi bisa diakses di browser),terus
          ##   ngepublish image yang udah di buat ke containernya
          ##5. containernya dijalankan
          script: |
            sudo docker container stop helloworld 
            sudo docker rm helloworld
            sudo docker pull catherinevania/helloworld:v${{ github.run_number }}
            sudo docker container create --name helloworld --publish 80:80 catherinevania/helloworld:v${{ github.run_number }}
            sudo docker container start helloworld
